basic_settings:
  site_title: Isadora T.
  favicon_image: /images/favicon.png

header_settings:
  ##logo_image: /images/logo2.jpg
  logo_image: /images/insta2.gif
  logo_width: 80

menu_settings:
  menu_items:
    - title: 'Portfolio'
      url: '/'
    - title: 'Journal'
      url: '/blog/'
    - title: 'Glossaire'
      url: '/glossaire'
    - title: 'Teaching'
      url: '/things/'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'
    

footer_settings:
  footer_tagline: Portfolio et notes de recherche-création

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 5
  content_alignment: bottom

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/isadoratelesdecastro/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: 'https://isadorateles.tumblr.com/'
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/isadorateles/'


color_settings:
  background_color:  '#ffffff'
  ##background_color:  '#ebdfd0'
  ##background_color: '#ebe2d3'
  background_alt_color: '#b2006b'
  ##text_dark_color: '#4fbca3'
  text_dark_color: '#000000'
  text_medium_color: '#000000'  
  text_light_color: '#000000'
  accent_color: '#bcba1c'
  border_color: '#80f0b4'
  overlay_background_color: '#8048b4'
  overlay_text_color: '#80f0b4'
  overlay_accent_color: '#fdc26b'
  error_color: '#ff297f'

font_settings:
  font_embed: '<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600&family=Merriweather:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,100;1,300;1,400;1,500&display=swap" rel="stylesheet">'
  title_font: '"Merriweather", serif'
  body_font: '"Roboto", serif'
  regular_weight: 300
  bold_weight: 300
  site_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 300
    letter_spacing: -0.02
  menu:
    small_size: 60
    medium_size: 28
    large_size: 30
    weight: 300
    letter_spacing: 0
  grid_item_title:
    small_size: 28
    medium_size: 28
    large_size: 28
    weight: 300
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 17
    medium_size: 17
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 300
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 20
    medium_size: 25
    large_size: 30
    weight: 300
    letter_spacing: -0.02
    line_height: 1.8
  h3:
    small_size: 18
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: -0.02
    line_height: 2.2
  h4:
    small_size: 16
    medium_size: 18
    large_size: 18
    weight: 300
    letter_spacing: 0
    line_height: 2.2
  h5:
    small_size: 16
    medium_size: 18
    large_size: 18
    weight: 300
    letter_spacing: 0
    line_height: 2.2
  h6:
    small_size: 16
    medium_size: 18
    large_size: 18
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 14
    medium_size: 16
    large_size: 18
    weight: 300
    letter_spacing: 0
    line_height: 1.8
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 300
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""